### ISSUE TITLE
a work in progress

### ISSUE THREAD

**Issue by camerondodd** [camerondodd/capstone2#1]
All right.

You can sign in with google+, if you have an account, it will GET it, else, it will POST a new one.  From the profile page, you can go to MyAccount, which has an option to use DELETE to delete your account.  I also have it set up, so it will be able to GET their stats on the profile page.

From the adv page in the view folder, which you get to from the profile page, they should be able to push a button to make a PUT request to update their account with a slightly higher stat, but it doesn't work.

I have only coded for the str button on adv.ejs, which links to index.js in the public folder, where strButton() run putStr(), which sends the PUT request to profileRoutes in the routes folder, which has a router.put that isn't working.

Also, while the DELETE does delete the account, it will not redirect to the login page.  It just stays on the account page.  I have tried redirecting from the router side and from the index side with delReD(), but nothing seems to work.

**Comment by krokhale** [comment]
Error: Cannot find module './keys'

I am guessing you did not add it to the repo which is fine, Can you email it to me?

**Comment by camerondodd** [comment]
Have a nice day,

Cameron Dodd, M.S.
Cameron.Dodd@mavs.uta.edu
________________________________

**Comment by krokhale** [comment]
I don't see the 'keys' in the commits. Am I missing something? Can we maybe just schedule a session, it should be quicker to resolve that way.

**Comment by camerondodd** [comment]
It isn't letting me send the file.  What is the harm of commiting something like this with all of the keys included?  I can just remove them later, right?


Have a nice day,

Cameron Dodd, M.S.
Cameron.Dodd@mavs.uta.edu
________________________________

**Comment by krokhale** [comment]
Committing it to the repo is not secure, there's loads of spiders that look around for public repos with keys in the commits. Can you just copy paste it and email it to me?

**Comment by camerondodd** [comment]
Ah! I got it.  I just needed to add


router.use(bodyParser.urlencoded({extended:true}));


and the bodyParser started to work, so I could access the new object.


I still need some help figuring out how to redirect to the homepage after you delete the account.


Have a nice day,

Cameron Dodd, M.S.
Cameron.Dodd@mavs.uta.edu
________________________________

**Comment by krokhale** [comment]
Cool! Redirect could be as simple as
 
    res.redirect('/url')

Though you might need to first log a user out in the browser, so that the session is cleaned in the browser and then maybe clear it on the server, including removing user record using mongoose:

https://stackoverflow.com/questions/31641884/does-passports-logout-function-remove-the-cookie-if-not-how-does-it-work

Also, i feel like deleting user account might not be central to the capstone, give it a couple of more hours and then maybe you can focus on the meat of the Capstone. I will try and run this today and let you know if i have any feedback.

**Comment by camerondodd** [comment]
I need to be able to do all four CRUD functions, and there really isn't any other data to delete besides the user account, so I wasn't sure what else to do.


That said, I have successfully gotten it to redirect to the login page when the account is deleted!  I have my CRUD and all my wire are connected.  I can finally actually start building the site.


Have a nice day,

Cameron Dodd, M.S.
Cameron.Dodd@mavs.uta.edu
________________________________

**Comment by krokhale** [comment]
Great work with the passport stuff, that can get a little tedious sometimes. Also, just created a pull request for a basic way to structure your API routes.

Off the topic, and not really covered by Thinkful(They expect you to do it with passport), but i would totally recommend something like Auth0 to create quick auth system integration:

https://auth0.com/

Also, since express apps allow a lot of freedom in structuring files/routes based on personal preferences, there is no one way to do things, but i would totally recommend having a look at:

https://github.com/sahat/hackathon-starter

Follow the instructions on the readme and create a dummy starter app. And just look at how the code is structured. It should help you in thinking about how to structure your apps.
